#!/bin/sh

export ORGCHKSM="5924c70e5c9fabf0398050349c3f4f283ab80091b23ea8c677249ee7bdd41f6e4910ce5e1bc32577e67763dc30d9b96cc3528256e1cc63dba959a5e3866ec21f"
export ORGFILE="/usr/share/initramfs-tools/scripts/local-top/cryptroot"


. /usr/share/debconf/confmodule

_nask_cmd () {
  db_get naskpass/active
  if [ "x$1" = "xACTV" ] && [ "$RET" = "false" ]; then
    if [ "${ORGCHKSM}" != "$(/usr/bin/sha512sum ${ORGFILE} | grep -Eo '^[0-9a-zA-Z]*')" ]; then
      export ERRMSG="$0: sha512sum mismatch"
      return 1
    fi
    dpkg-divert --package naskpass --add --rename --divert /var/backups/cryptroot.initramfs.bak ${ORGFILE}
    cp /usr/share/naskpass/naskpass.script.initramfs ${ORGFILE}
    ln -s /usr/share/naskpass/naskpass.hook.initramfs \
      /usr/share/initramfs-tools/hooks/naskpass
    db_set naskpass/active true
  elif [ "x$1" = "xDCTV" ] && [ "$RET" = "true" ]; then
    rm ${ORGFILE}
    rm /usr/share/initramfs-tools/hooks/naskpass
    dpkg-divert --package naskpass --rename --remove ${ORGFILE}
    db_set naskpass/active false
  fi
  return 0
}

nask_activate ()	{ _nask_cmd "ACTV"; return $?; }
nask_deactivate ()	{ _nask_cmd "DCTV"; return $?; }
